spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ch
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:${user.dir}/src/main/resources/static/
#上传文件路径
uploadFilePath:
  bannerPicturesPath: ${user.dir}/src/main/resources/static/bannerPictures
  productPicturesPath: ${user.dir}/src/main/resources/static/productPictures
  heritagePicturesPath: ${user.dir}/src/main/resources/static/heritagePictures
  heritageMaterialPath: ${user.dir}/src/main/resources/static/heritageMaterial